@startuml
start
:Afficher "⚔️ Combat entre joueur et entraineurAdversaire commence !";

while ((!avoirGagne() && !avoirPerdu())) is (oui)
    :monstreJoueur = joueur.choisirMonstre();
    :monstreAdverse = un monstre vivant au hasard de entraineurAdversaire;

    :Afficher "${joueur.nom} envoie monstreJoueur";
    :Afficher "${entraineurAdversaire.nom} envoie monstreAdverse";

    :combat = CombatMonstre(monstreJoueur, monstreAdverse);
    :combat.lanceCombat();
endwhile (non)

if (avoirGagne()) then (oui)
    :recompense = entraineurAdversaire.argents / 2;
    :Afficher victoire et gain;
    :joueur.argents += recompense;
    stop
else (non)
    :Afficher défaite;
    :joueur.soignerEquipe();
    :entraineurAdversaire.soignerEquipe();
    stop
endif
@enduml
